### ISSUE TITLE
CancelToken.cancel() on requestStream causes "Unhandled Exception: RhttpError.rhttpCancelError()"

### ISSUE THREAD

**Issue by xalanq** [Tienisto/rhttp#38]
Steps to reproduce:
1. edit `rhttp/example/lib/cancellation.dart` line 45 `requestBytes` to `requestStream`
2. copy `rhttp/example/lib/cancellation.dart` to `rhttp/example/lib/main.dart`
3. run example
4. press `Cancel after 1 second`

Then you will see the unhandled exception
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RhttpError.rhttpCancelError()
#0      SimpleDecoder.decode
package:flutter_rust_bridge/…/codec/base.dart:32
#1      SseCodec._decode
package:flutter_rust_bridge/…/codec/sse.dart:45
#2      SseCodec.decodeObject
package:flutter_rust_bridge/…/codec/sse.dart:35
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:861:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:890:13)
#5      Future._completeWithValue (dart:async/future_impl.dart:666:5)
#6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:736:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by Tienisto** [comment]
Fixed in `v0.9.2`

**Comment by Tienisto** [comment]
Thanks for noticing this. It should be safe enough because errors are thrown in `await responseCompleter.future` and `await responseFuture` anyways.

**Comment by xalanq** [comment]
Hi, could you release 0.9.3 to pub.dev? Thanks!

**Comment by Tienisto** [comment]
Sure
